In [8]:
import keras as k
import scipy

In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.models import model_from_json

from keras.models import Sequential
from keras.layers import Dense, Activation
import pickle
import matplotlib.pyplot as plt
%matplotlib inline

dumpfiles(home=home, fsize=9, phi=0.1, dp = 75, timestep=0.6)

dumpfiles(home=home, fsize=9, phi=0.1, dp = 75, timestep=0.65)

dumpfiles(home=home, fsize=9, phi=0.1, dp = 150, timestep=0.65)

dumpfiles(home=home, fsize=9, phi=0.1, dp = 300, timestep=0.65)

dumpfiles(home=home, fsize=9, phi=0.3, dp = 75, timestep=0.425)

In [4]:
home = '/home/nandhini/aozel/periodicBox'
fsize = 9
phi=0.1
dp = 75

data_signature1 = 'fsize' + str(fsize)+'phi'+str(phi)+'dp'+str(dp)+'timestep'+str(0.6)
data_signature2 = 'fsize' + str(fsize)+'phi'+str(phi)+'dp'+str(dp)+'timestep'+str(0.7)
data_signature3 = 'fsize' + str(9)+'phi'+str(0.3)+'dp'+str(75)+'timestep'+str(0.4)
data_signature4 = 'fsize' + str(9)+'phi'+str(0.1)+'dp'+str(300)+'timestep'+str(0.65)
data_signature5 = 'fsize' + str(9)+'phi'+str(0.1)+'dp'+str(150)+'timestep'+str(0.65)
data_signature6 = 'fsize' + str(9)+'phi'+str(0.3)+'dp'+str(75)+'timestep'+str(0.3) + 'HighCoh'




file_myData1 = "myDataUslip"+data_signature1+".pickle"
file_myData2 = "myDataUslip"+data_signature2+".pickle"
file_myData3 = "myDataUslip"+data_signature3+".pickle"
file_myData4 = "myDataUslip"+data_signature4+".pickle"
file_myData5 = "myDataUslip"+data_signature5+".pickle"
file_myData6 = "myDataUslip"+data_signature6+".pickle"





file_target1 = "targetUslip"+data_signature1+".pickle"
file_target2 = "targetUslip"+data_signature2+".pickle"
file_target3 = "targetUslip"+data_signature3+".pickle"
file_target4 = "targetUslip"+data_signature4+".pickle"
file_target5 = "targetUslip"+data_signature5+".pickle"
file_target6 = "targetUslip"+data_signature6+".pickle"




myData1 = pickle.load( open( file_myData1, "rb" ) )

                

target1 = pickle.load( open( file_target1, "rb" ) )

In [5]:
myData1.shape, target1.shape

((1934712, 108), (1934712,))

In [18]:
rf = RandomForestRegressor(n_jobs=-1,n_estimators=100)

In [19]:
rf.fit(myData1, target1)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=-1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [26]:
np.argsort(rf.feature_importances_)[::-1]

array([107,  96,  68,  75,  28,  52,  44,  24,  64,  20,  39, 100, 101,
        61,  45,  27,  62,  41,  87,  91,  43,  54,  18,  89, 106,   1,
        67,  30,  77,   7,  42,  86,  21,  34,  70,  51, 102,  31,  94,
        79,  74, 103,  66,  84,  33,   5,  99,  38,  23,  53,  56,   6,
        76,  72,  46,  57,  35,  71,  60,  47,  10,  32,  14,  78,  95,
        17,  63,  82,   3,  88,  93,  73,  58,  48,  55,  15,   4,  83,
        80,  98,  40,   0, 104,  90, 105,  26,   2,  11,  59,  19,  49,
         9,  92,  50,  69,   8,  25,  36,  29,  16,  37,  81,  97,  22,
        12,  65,  85,  13])

In [27]:
np.argsort(rf.feature_importances_)

array([ 13,  85,  65,  12,  22,  97,  81,  37,  16,  29,  36,  25,   8,
        69,  50,  92,   9,  49,  19,  59,  11,   2,  26, 105,  90, 104,
         0,  40,  98,  80,  83,   4,  15,  55,  48,  58,  73,  93,  88,
         3,  82,  63,  17,  95,  78,  14,  32,  10,  47,  60,  71,  35,
        57,  46,  72,  76,   6,  56,  53,  23,  38,  99,   5,  33,  84,
        66, 103,  74,  79,  94,  31, 102,  51,  70,  34,  21,  86,  42,
         7,  77,  30,  67,   1, 106,  89,  18,  54,  43,  91,  87,  41,
        62,  27,  45,  61, 101, 100,  39,  20,  64,  24,  44,  52,  28,
        75,  68,  96, 107])

In [23]:
np.sort(rf.feature_importances_)

array([  2.23703486e-05,   2.32750197e-05,   2.51818543e-05,
         2.70856769e-05,   2.73575371e-05,   3.62373481e-05,
         3.68479749e-05,   3.69140488e-05,   3.97956569e-05,
         5.08248668e-05,   6.17335414e-05,   6.30132224e-05,
         6.37606181e-05,   6.44275518e-05,   6.52290033e-05,
         6.87451697e-05,   6.89452728e-05,   7.06688152e-05,
         7.66045869e-05,   7.84536278e-05,   8.31096266e-05,
         8.39280105e-05,   8.47321148e-05,   8.57002904e-05,
         1.03839056e-04,   1.08897930e-04,   1.10216645e-04,
         1.20079815e-04,   1.23773098e-04,   1.25679642e-04,
         1.30737004e-04,   1.31940211e-04,   1.51204761e-04,
         1.53400731e-04,   1.56176543e-04,   1.57236042e-04,
         1.81921949e-04,   1.84729750e-04,   1.89361257e-04,
         1.94115350e-04,   1.99589774e-04,   2.02291653e-04,
         2.19354281e-04,   2.31150879e-04,   2.32791032e-04,
         2.42041904e-04,   2.52745669e-04,   2.61630155e-04,
         2.88602684e-04,

In [5]:
X_train, X_test, y_train, y_test = train_test_split(myData, target, test_size=0.02, random_state=42)
X_realCV, X_realTT, y_realCV, y_realTT = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

In [6]:
scaler = StandardScaler()
scaler.fit(X_train)
pickle.dump( scaler, open( 'scale'+data_signature1, "wb" ) )
X_train_norm = scaler.transform(X_train)
X_realCV_norm = scaler.transform(X_realCV)
X_realTT_norm = scaler.transform(X_realTT)

In [19]:
np.savetxt("drag_std.csv", scaler.std_, delimiter=",")
np.savetxt("drag_mean.csv", scaler.mean_, delimiter=",")

/home/hema/yile/anaconda3/lib/python3.5/site-packages/sklearn/utils/deprecation.py:70: DeprecationWarning: Function std_ is deprecated; Attribute ``std_`` will be removed in 0.19. Use ``scale_`` instead
  warnings.warn(msg, category=DeprecationWarning)


In [ ]:
X_train_norm.shape, X_realCV_norm.shape, X_realTT_norm.shape

((11376106, 108), (116083, 108), (116083, 108))

In [55]:
model = Sequential()
model.add(Dense(100, activation='relu', kernel_initializer='normal',input_dim=X_train_norm.shape[-1]))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(64, activation='relu', kernel_initializer='normal'))
model.add(Dense(64, activation='relu', kernel_initializer='normal'))
model.add(Dense(64, activation='relu', kernel_initializer='normal'))
model.add(Dense(32, activation='relu', kernel_initializer='normal'))
model.add(Dense(16, activation='relu', kernel_initializer='normal'))
model.add(Dense(8, activation='relu', kernel_initializer='normal'))
model.add(Dense(4, activation='relu', kernel_initializer='normal'))
model.add(Dense(1, activation='linear', kernel_initializer='normal'))
model.compile(loss='mean_absolute_error', optimizer='Adam')
save_file = 'weights_Uslip3'+ data_signature1 + '.hdf5'
model.load_weights(save_file)
checkpointer = ModelCheckpoint(filepath=save_file, verbose=1, save_best_only=True)
#model.fit(X_train_norm, y_train, batch_size=1000, epochs=40, verbose=1, validation_data=(X_realCV_norm, y_realCV), callbacks=[checkpointer])

In [56]:
# serialize model to JSON
model_json = model.to_json()
with open("drag2.json", "w") as json_file:
    json_file.write(model_json)

In [15]:
data_signature1

'fsize9phi0.1dp75timestep0.6'

In [52]:
model.predict(np.array([[2.70287, 0.0280261, 1.23125, -0.769839, 2.70308, 0.0279703, 1.23075, -0.769849, 2.70327, 0.0278884, 1.23002, -0.769865, 2.70358, 0.0282558, 1.23087, -0.769851, 2.70378, 0.0281992, 1.23037, -0.769862, 2.70398, 0.0281165, 1.22965, -0.769879, 2.7043, 0.0284953, 1.23039, -0.769917, 2.70451, 0.0284387, 1.2299, -0.76993, 2.70471, 0.0283554, 1.22919, -0.769949, 2.70326, 0.0279363, 1.23085, -0.769817, 2.70346, 0.027879, 1.23035, -0.769827, 2.70366, 0.027796, 1.22961, -0.769845, 2.70396, 0.0281659, 1.23047, -0.769828, 2.70417, 0.0281084, 1.22998, -0.76984, 2.70437, 0.0280249, 1.22925, -0.769858, 2.70468, 0.0284036, 1.22999, -0.769895, 2.70489, 0.0283462, 1.22951, -0.769908, 2.70509, 0.0282624, 1.22879, -0.769928, 2.70362, 0.0278401, 1.2305, -0.769814, 2.70383, 0.0277819, 1.22999, -0.769825, 2.70403, 0.0276979, 1.22925, -0.769844, 2.70432, 0.028069, 1.23012, -0.769824, 2.70453, 0.0280113, 1.22962, -0.769836, 2.70473, 0.0279274, 1.22889, -0.769856, 2.70504, 0.0283043, 1.22965, -0.769891, 2.70525, 0.028247, 1.22915, -0.769905, 2.70545, 0.0281631, 1.22843, -0.769926]]))

array([[ 1.28914738]], dtype=float32)

In [53]:
a = np.array([[-1.16182, 0.0280261, 1.23125, -0.769839, -1.16181, 0.0279703, 1.23075, -0.769849, -1.16182, 0.0278884, 1.23002, -0.769865, -1.16182, 0.0282558, 1.23087, -0.769851, -1.16182, 0.0281992, 1.23037, -0.769862, -1.16183, 0.0281165, 1.22965, -0.769879, -1.16177, 0.0284953, 1.23039, -0.769917, -1.16177, 0.0284387, 1.2299, -0.76993, -1.16178, 0.0283554, 1.22919, -0.769949, -1.16171, 0.0279363, 1.23085, -0.769817, -1.16171, 0.027879, 1.23035, -0.769827, -1.16171, 0.027796, 1.22961, -0.769845, -1.16171, 0.0281659, 1.23047, -0.769828, -1.16171, 0.0281084, 1.22998, -0.76984, -1.16172, 0.0280249, 1.22925, -0.769858, -1.16166, 0.0284036, 1.22999, -0.769895, -1.16166, 0.0283462, 1.22951, -0.769908, -1.16167, 0.0282624, 1.22879, -0.769928, -1.16162, 0.0278401, 1.2305, -0.769814, -1.16161, 0.0277819, 1.22999, -0.769825, -1.16162, 0.0276979, 1.22925, -0.769844, -1.16161, 0.028069, 1.23012, -0.769824, -1.16161, 0.0280113, 1.22962, -0.769836, -1.16162, 0.0279274, 1.22889, -0.769856, -1.16156, 0.0283043, 1.22965, -0.769891, -1.16156, 0.028247, 1.22915, -0.769905, -1.16157, 0.0281631, 1.22843, -0.769926]])

In [54]:
model.predict(a)

array([[-0.33250952]], dtype=float32)

In [ ]:
model = Sequential()

model.add(Dense(100, activation='relu', kernel_initializer='normal',input_dim=X_train_norm.shape[-1]))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(100, activation='relu', kernel_initializer='normal'))
model.add(Dense(64, activation='relu', kernel_initializer='normal'))
model.add(Dense(64, activation='relu', kernel_initializer='normal'))
model.add(Dense(64, activation='relu', kernel_initializer='normal'))
model.add(Dense(32, activation='relu', kernel_initializer='normal'))
model.add(Dense(16, activation='relu', kernel_initializer='normal'))
model.add(Dense(8, activation='relu', kernel_initializer='normal'))
model.add(Dense(4, activation='relu', kernel_initializer='normal'))
model.add(Dense(1, activation='linear', kernel_initializer='normal'))
model.compile(loss='mean_absolute_error', optimizer='Adam')
save_file = 'weights_Uslip3'+ data_signature1 + '.hdf5'
model.load_weights(save_file)
checkpointer = ModelCheckpoint(filepath=save_file, verbose=1, save_best_only=True)
#model.fit(X_train_norm, y_train, batch_size=1000, epochs=40, verbose=1, validation_data=(X_realCV_norm, y_realCV), callbacks=[checkpointer])

In [ ]:
# serialize model to JSON
model_json = model.to_json()
with open("drag2.json", "w") as json_file:
    json_file.write(model_json)

In [57]:
model = Sequential()
model.add(Dense(100,input_dim=108))
model.add(Activation('relu'))
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dense(100))
model.add(Activation('relu'))

model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dense(64))
model.add(Activation('relu'))

model.add(Dense(32))
model.add(Activation('relu'))

model.add(Dense(16))
model.add(Activation('relu'))

model.add(Dense(8))
model.add(Activation('relu'))

model.add(Dense(4))
model.add(Activation('relu'))

model.add(Dense(1))
model.compile(loss='mean_absolute_error', optimizer='Adam')
save_file = 'weights_Uslip3'+ data_signature1 + '.hdf5'
model.load_weights(save_file)

In [58]:
# serialize model to JSON
model_json = model.to_json()
with open("drag_correct.json", "w") as json_file:
    json_file.write(model_json)