In [1]:
import keras as k
import scipy
import numpy as np
import pandas as pd
import pickle

Using Theano backend.


In [2]:
def get_scaler_openfoam(home,file,fsize):
    file = file + str(fsize) + 'X' + str(fsize) + 'X' + str(fsize)
    data = pd.read_csv(home+file,skiprows=21,skipfooter=33)
    data = data.values
    return data
    


In [3]:
def get_vector_openfoam(home,file,fsize):
    file = file + str(fsize) + 'X' + str(fsize) + 'X' + str(fsize)
    data = pd.read_csv(home+file,skiprows=21,skipfooter=33)
    data = data.values
    data = np.array([[float(x[0].split()[0][1:]), float(x[0].split()[1]), float(x[0].split()[2][:-1])] for x in data])
    return data

In [4]:
def dumpfiles(home, fsize, timestep):
    home = home + '/' + str(timestep) + '/'
    numpy_barAlpp = get_scaler_openfoam(home,'barAlpp',fsize)
    numpy_tildeUs = get_vector_openfoam(home,'tildeUs',fsize)
    numpy_tildeUf = get_vector_openfoam(home,'tildeUf',fsize)
    numpy_barAlppVdrift = get_vector_openfoam(home,'barAlppVdrift',fsize)
    numpy_Xsgs = get_vector_openfoam(home,'Xsgs',fsize)
    #numpy_Ysgs = get_vector_openfoam(home,'Ysgs',fsize)
    
    numpy_Uslip = numpy_tildeUf - numpy_tildeUs

    original_table = np.concatenate((numpy_barAlpp,numpy_Uslip,numpy_barAlppVdrift ),axis=1)

    nx = 80
    ny = 80
    nz = 320
    dx = 1

    index1=0
    npData=original_table.shape[-1]

    myData = np.zeros( ((nx-2)*(ny-2)*(nz-2), npData * (2*dx +1)**3) );
    target = np.zeros((nx-2)*(ny-2)*(nz-2))
    for i in range(1,nx-1):
        for j in range(1,ny-1):
            for k in range(1,nz-1):


                index2 = 0;
                for ii in range(-dx,dx+1):
                    for jj in range(-dx,dx+1):
                        for kk in range(-dx,dx+1):
                            stencil= i+ii + (j+jj)*nx + (k+kk)*nx*ny;
                            target[index1] = numpy_Xsgs[stencil,-1]
                            temp = original_table[stencil][:]
                            for ind in range(npData):
                                myData[index1,index2] = temp[ind];
                                index2 = index2 + 1
                index1 = index1 +1   
    myData = np.hstack((np.ones((myData.shape[0],1))*(1/(3*fsize)),myData))
    file_myData = "myData_vdrift"+'fsize' + str(fsize)+'timestep'+str(timestep)+".pickle"
    file_target = "target_vdrift"+'fsize' + str(fsize)+'timestep'+str(timestep)+".pickle"
    pickle.dump( myData, open( file_myData, "wb" ) )
    pickle.dump( target, open( file_target, "wb" ) )
    return myData

In [5]:
home = '/home/nandhini/yundij/neural_network'

In [6]:
dumpfiles(home=home, fsize=9, timestep=0.3)

/home/hema/yile/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  app.launch_new_instance()


array([[ 0.03703704,  0.0211182 ,  0.22789   , ..., -0.00156283,
        -0.00074387, -0.00161213],
       [ 0.03703704,  0.0214844 ,  0.210855  , ..., -0.00166211,
        -0.00088517, -0.001806  ],
       [ 0.03703704,  0.0220235 ,  0.187866  , ..., -0.00179665,
        -0.00126672, -0.00254654],
       ..., 
       [ 0.03703704,  0.0180045 ,  0.407704  , ..., -0.0028608 ,
        -0.00115907, -0.00413342],
       [ 0.03703704,  0.018138  ,  0.400299  , ..., -0.00270226,
        -0.00113504, -0.00394154],
       [ 0.03703704,  0.0186405 ,  0.379785  , ..., -0.00259585,
        -0.00113334, -0.00370166]])

In [7]:
dumpfiles(home=home, fsize=9, timestep=0.4)

/home/hema/yile/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  app.launch_new_instance()


array([[ 0.03703704,  0.0244372 ,  0.13822826, ..., -0.00286308,
         0.00793548, -0.0097281 ],
       [ 0.03703704,  0.0312508 ,  0.1224939 , ..., -0.00194016,
         0.00752028, -0.00857356],
       [ 0.03703704,  0.03814   ,  0.1003297 , ..., -0.00090292,
         0.00641462, -0.00731541],
       ..., 
       [ 0.03703704,  0.00585147,  0.2009544 , ..., -0.00043775,
         0.00122347, -0.00256333],
       [ 0.03703704,  0.00635617,  0.1652898 , ..., -0.0004965 ,
         0.00202261, -0.00325184],
       [ 0.03703704,  0.00728664,  0.1358431 , ..., -0.00073937,
         0.00320754, -0.00456051]])

In [8]:
dumpfiles(home=home, fsize=9, timestep=0.35)

/home/hema/yile/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  app.launch_new_instance()


array([[ 0.03703704,  0.153036  , -0.015017  , ..., -0.0017121 ,
         0.00712525, -0.0309993 ],
       [ 0.03703704,  0.142752  , -0.014868  , ..., -0.0018397 ,
         0.00776543, -0.0298717 ],
       [ 0.03703704,  0.141167  , -0.010747  , ..., -0.00203592,
         0.00871564, -0.0289903 ],
       ..., 
       [ 0.03703704,  0.199601  , -0.027002  , ...,  0.00306632,
         0.00451806, -0.00962852],
       [ 0.03703704,  0.187785  , -0.030488  , ...,  0.00427899,
         0.00460013, -0.00845195],
       [ 0.03703704,  0.172717  , -0.040815  , ...,  0.00469806,
         0.00407464, -0.00703807]])

In [ ]:
dumpfiles(home=home, dp = 300, timestep=0.6, fsize=9)

In [ ]:
dumpfiles(home=home, dp = 150, timestep=0.55, fsize=11)

In [ ]:
dumpfiles(home=home, dp = 75, timestep=0.65, fsize=13)

In [ ]:
dumpfiles(home=home, dp = 75, timestep=0.325, fsize=13,phi=0.3, cohesion='HighCoh')